name: alephclient

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        pip install setuptools
        make install
    - name: Run the tests
      run: make test
    - name: Validate typing
      run: make typecheck
    - name: Build a distribution
      run: make dists
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
