name: Run linter & formatting check

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v1
        with:
          args: "check"

      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

